import { trpc } from "@/lib/trpc";
import { displayDate, localDateInput, parseInputDate, phaseColors, phaseLabels } from "@/lib/redtent";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CirclePlus, Loader2, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { ErrorState } from "./Home";

export default function CyclePage() {
  const utils = trpc.useUtils();
  const [visibleMonth, setVisibleMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [showForm, setShowForm] = useState(false);
  const [startAt, setStartAt] = useState(localDateInput());
  const [endAt, setEndAt] = useState("");
  const [flow, setFlow] = useState<"spotting" | "light" | "medium" | "heavy">("medium");
  const [notes, setNotes] = useState("");
  const range = useMemo(() => ({ startAt: new Date(visibleMonth.getFullYear(), visibleMonth.getMonth(), 1), endAt: new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 0) }), [visibleMonth]);
  const summaryQuery = trpc.cycles.summary.useQuery();
  const marksQuery = trpc.cycles.calendar.useQuery(range);
  const create = trpc.cycles.create.useMutation({ onSuccess: async () => { await Promise.all([utils.cycles.summary.invalidate(), utils.cycles.calendar.invalidate(), utils.dashboard.overview.invalidate()]); toast.success("Period log saved"); setShowForm(false); setEndAt(""); setNotes(""); }, onError: error => toast.error(error.message) });
  const remove = trpc.cycles.delete.useMutation({ onSuccess: async () => { await Promise.all([utils.cycles.summary.invalidate(), utils.cycles.calendar.invalidate(), utils.dashboard.overview.invalidate()]); toast.success("Period log removed"); }, onError: error => toast.error(error.message) });
  if (summaryQuery.isLoading || marksQuery.isLoading) return <div className="mx-auto max-w-6xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>;
  if (summaryQuery.error || marksQuery.error || !summaryQuery.data || !marksQuery.data) return <ErrorState title="Your cycle view couldn’t be loaded" detail="Please check your connection and try again." />;
  const { summary, logs } = summaryQuery.data;
  const dateTitle = new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(visibleMonth);
  const leading = (range.startAt.getDay() + 6) % 7;

  return <div className="mx-auto max-w-6xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your rhythm</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Cycle calendar</h1><p className="mt-2 text-sm text-[#806A63]">Predictions are estimates based on your logged cycles.</p></div><button onClick={() => setShowForm(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#A84D5F] px-4 py-3 text-sm font-semibold text-white transition hover:bg-[#8F3F50]"><CirclePlus className="h-4 w-4" /> Log period</button></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="Current day" value={`Day ${summary.cycleDay}`} detail={`${phaseLabels[summary.phase]} phase`} /><Stat label="Typical cycle" value={`${summary.averageCycleLength} days`} detail={`Median ${summary.medianCycleLength} days`} /><Stat label="Pattern variation" value={summary.variation ? `${summary.variation} days` : "Still learning"} detail={summary.confidence === "building" ? "Keep logging to improve estimates" : `${summary.confidence} confidence`} /></section>
    <section className="rose-card mt-6 p-4 sm:p-6"><div className="flex items-center justify-between"><button onClick={() => setVisibleMonth(new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1))} className="grid h-9 w-9 place-items-center rounded-full hover:bg-[#F5E8E3]"><ChevronLeft className="h-5 w-5" /></button><h2 className="font-display text-xl sm:text-2xl">{dateTitle}</h2><button onClick={() => setVisibleMonth(new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1))} className="grid h-9 w-9 place-items-center rounded-full hover:bg-[#F5E8E3]"><ChevronRight className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-[11px] font-bold uppercase tracking-wide text-[#9B827A]">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <div key={day} className="py-1">{day}</div>)}</div><div className="grid grid-cols-7 gap-1">{Array.from({ length: leading }).map((_, index) => <div key={`empty-${index}`} className="aspect-square" />)}{marksQuery.data.map(mark => <CalendarDay key={mark.date.toString()} mark={mark} />)}</div><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[#806A63]"><Legend className="bg-[#C66E78]" text="Logged period" /><Legend className="border border-dashed border-[#C66E78] bg-[#FFF3F3]" text="Estimated period" /><Legend className="bg-[#F8E1B3]" text="Follicular" /><Legend className="bg-[#DED0DF]" text="Luteal" /></div></section>
    <section className="mt-7"><div className="flex items-end justify-between"><div><p className="eyebrow">History</p><h2 className="mt-1 font-display text-2xl">Period logs</h2></div></div>{logs.length ? <div className="mt-4 grid gap-3">{logs.map(log => <article key={log.id} className="rose-card flex items-center justify-between gap-4 p-4"><div><p className="font-semibold">{displayDate(log.startAt, { month: "long", day: "numeric", year: "numeric" })}{log.endAt ? ` – ${displayDate(log.endAt)}` : " · ongoing"}</p><p className="mt-1 text-xs capitalize text-[#8C746C]">{log.flow || "Flow not set"}{log.notes ? ` · ${log.notes}` : ""}</p></div><button disabled={remove.isPending} onClick={() => remove.mutate({ id: log.id })} className="grid h-9 w-9 place-items-center rounded-xl text-[#B04D5C] hover:bg-[#FBE9E9]" aria-label="Delete cycle log"><Trash2 className="h-4 w-4" /></button></article>)}</div> : <div className="rose-card mt-4 p-6 text-sm leading-6 text-[#806A63]">Your future calendar will become more personal as you add period dates.</div>}</section>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-end bg-[#3E2527]/35 p-0 sm:place-items-center sm:p-5"><form onSubmit={event => { event.preventDefault(); create.mutate({ startAt: parseInputDate(startAt), endAt: endAt ? parseInputDate(endAt) : null, flow, notes: notes || null }); }} className="w-full max-w-lg rounded-t-[2rem] bg-[#FFFDFB] p-6 shadow-2xl sm:rounded-[2rem]"><div className="flex items-start justify-between"><div><p className="eyebrow">Cycle log</p><h2 className="mt-1 font-display text-2xl">Log your period</h2></div><button type="button" onClick={() => setShowForm(false)} className="text-sm font-semibold text-[#8B7269]">Cancel</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Start date"><input required value={startAt} onChange={e => setStartAt(e.target.value)} type="date" className="field-input" /></Field><Field label="End date (optional)"><input value={endAt} onChange={e => setEndAt(e.target.value)} min={startAt} type="date" className="field-input" /></Field></div><Field label="Flow" className="mt-4"><select value={flow} onChange={e => setFlow(e.target.value as typeof flow)} className="field-input"><option value="spotting">Spotting</option><option value="light">Light</option><option value="medium">Medium</option><option value="heavy">Heavy</option></select></Field><Field label="Private note (optional)" className="mt-4"><textarea value={notes} onChange={e => setNotes(e.target.value)} maxLength={2000} className="field-input min-h-24 resize-none" placeholder="Anything you’d like to remember?" /></Field><button disabled={create.isPending} className="mt-6 flex w-full items-center justify-center rounded-xl bg-[#A84D5F] py-3 text-sm font-semibold text-white disabled:opacity-60">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save period log"}</button></form></div>}
  </div>;
}

function CalendarDay({ mark }: { mark: { date: Date; cycleDay: number | null; phase: "menstrual" | "follicular" | "ovulation" | "luteal" | null; isLoggedPeriod: boolean; isPredictedPeriod: boolean } }) { const today = new Date(); const isToday = mark.date.toDateString() === today.toDateString(); const background = mark.isLoggedPeriod ? "bg-[#C66E78] text-white" : mark.isPredictedPeriod ? "border border-dashed border-[#C66E78] bg-[#FFF3F3] text-[#A64B5C]" : mark.phase === "follicular" ? "bg-[#F8E1B3]" : mark.phase === "ovulation" ? "bg-[#DCE9D9]" : mark.phase === "luteal" ? "bg-[#DED0DF]" : mark.phase === "menstrual" ? "bg-[#F8E8E5]" : "border border-[#F0E5DF] bg-[#FFFCFA] text-[#9A837A]"; return <div className={`relative flex aspect-square min-h-10 flex-col items-center justify-center rounded-xl text-xs sm:min-h-14 ${background} ${isToday ? "ring-2 ring-[#513039] ring-offset-2" : ""}`} title={mark.phase ? `${phaseLabels[mark.phase]} · cycle day ${mark.cycleDay}` : "No cycle data yet"}><span className="font-bold">{mark.date.getDate()}</span>{mark.cycleDay && <span className="mt-0.5 hidden text-[9px] opacity-75 sm:block">D{mark.cycleDay}</span>}</div>; }
function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rose-card p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#997D74]">{label}</p><p className="mt-2 text-lg font-bold">{value}</p><p className="mt-1 text-xs text-[#806A63]">{detail}</p></div>; }
function Legend({ className, text }: { className: string; text: string }) { return <span className="inline-flex items-center gap-2"><i className={`h-3 w-3 rounded-full ${className}`} />{text}</span>; }
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#7E655D]">{label}</span>{children}</label>; }
