import { trpc } from "@/lib/trpc";
import { phaseColors, phaseDescriptions, phaseLabels } from "@/lib/redtent";
import { Loader2, ShieldCheck } from "lucide-react";
import { ErrorState } from "./Home";

const phaseCards = [
  { phase: "menstrual", focus: "Gentle replenishment", text: "If this suits your usual diet, iron-containing foods, vitamin C sources, fluids, and protein can be practical building blocks.", foods: ["Beans and lentils", "Leafy greens", "Eggs", "Citrus"] },
  { phase: "follicular", focus: "Fresh energy", text: "Balanced meals with protein, colourful plants, and satisfying carbohydrates can support an adaptable routine.", foods: ["Whole grains", "Yogurt or alternatives", "Vegetables", "Nuts and seeds"] },
  { phase: "ovulation", focus: "Nourish and hydrate", text: "Regular meals and fluids can be useful anchors. Fibre-rich plants and protein are flexible options to explore.", foods: ["Tomatoes", "Chickpeas", "Fish or tofu", "Cucumber"] },
  { phase: "luteal", focus: "Steady comfort", text: "Regular, satisfying meals may feel supportive. Foods with fibre, magnesium, protein, and healthy fats are options—not rules.", foods: ["Oats", "Avocado", "Pumpkin seeds", "Dark leafy greens"] },
] as const;

export default function GuidancePage() { const overview = trpc.dashboard.overview.useQuery(); if (overview.isLoading) return <div className="mx-auto max-w-6xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>; if (overview.error || !overview.data) return <ErrorState title="Guidance couldn’t be loaded" detail="Please check your connection and try again." />; const activePhase = overview.data.summary.phase; return <div className="mx-auto max-w-6xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9"><header><p className="eyebrow">Nutrition guidance</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Food support, not food rules.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#806A63]">Cycle phases can be one gentle lens for planning meals. Your tastes, culture, budget, health history, and hunger matter more than any universal plan.</p></header><section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#E9D8DD] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className={`phase-pill ${phaseColors[activePhase]}`}>Your current phase: {phaseLabels[activePhase]}</span><h2 className="mt-4 font-display text-3xl">{overview.data.guidance.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#624C53]">{overview.data.guidance.description}</p></div><ShieldCheck className="h-11 w-11 text-[#8B5260]" /></div><div className="mt-5 flex flex-wrap gap-2">{overview.data.guidance.foods.map(food => <span key={food} className="rounded-full bg-white/70 px-3 py-2 text-xs font-bold text-[#754D56]">{food}</span>)}</div></section><section className="mt-8 grid gap-4 md:grid-cols-2">{phaseCards.map(card => <article key={card.phase} className={`rose-card p-5 ${card.phase === activePhase ? "ring-2 ring-[#D48691]" : ""}`}><div className="flex items-center justify-between"><span className={`phase-pill ${phaseColors[card.phase]}`}>{phaseLabels[card.phase]}</span>{card.phase === activePhase && <span className="text-xs font-bold text-[#A74D5C]">Current</span>}</div><h2 className="mt-4 font-display text-2xl">{card.focus}</h2><p className="mt-3 text-sm leading-6 text-[#785F57]">{card.text}</p><div className="mt-4 flex flex-wrap gap-2">{card.foods.map(food => <span key={food} className="rounded-full bg-[#F8ECE8] px-3 py-1.5 text-xs font-semibold text-[#815E56]">{food}</span>)}</div><p className="mt-5 border-t border-[#EEE0DB] pt-4 text-xs leading-5 text-[#987D75]">{phaseDescriptions[card.phase]}</p></article>)}</section><aside className="mt-7 rounded-2xl bg-[#F6F0EA] p-5 text-sm leading-6 text-[#735D55]"><strong>Keep the context close.</strong> These are general wellness ideas, not a prescription or treatment. Food-image estimates may be inaccurate; if nutrition or cycle symptoms are a health concern, a qualified clinician or registered dietitian can offer individual support.</aside></div>; }
