import { trpc } from "@/lib/trpc";
import { copy, phaseColors, phaseDescriptions, phaseLabels } from "@/lib/redtent";
import { Loader2, ShieldCheck } from "lucide-react";
import { ErrorState } from "./Home";

const phaseCards = [
  { phase: "menstrual", focus: "Replenish with intention", text: "Build meals that feel steady and restoring. Iron-containing foods, vitamin C sources, fluids, and protein can be useful options if they suit your normal way of eating.", foods: ["Beans and lentils", "Leafy greens", "Eggs", "Citrus"] },
  { phase: "follicular", focus: "Build your momentum", text: "As your energy shifts, explore meals with satisfying protein, colourful plants, and carbohydrates that help you feel ready for the day.", foods: ["Whole grains", "Yogurt or alternatives", "Vegetables", "Nuts and seeds"] },
  { phase: "ovulation", focus: "Stay nourished and steady", text: "Keep your routine simple. Regular meals, fluids, fibre-rich plants, and protein can be flexible anchors when life gets full.", foods: ["Tomatoes", "Chickpeas", "Fish or tofu", "Cucumber"] },
  { phase: "luteal", focus: "Choose comfort that lasts", text: "Make room for satisfying meals that help you feel grounded. Fibre, magnesium, protein, and healthy fats are options to explore, never rules to follow.", foods: ["Oats", "Avocado", "Pumpkin seeds", "Dark leafy greens"] },
] as const;

export default function GuidancePage() {
  const overview = trpc.dashboard.overview.useQuery();
  if (overview.isLoading) return <div className="mx-auto max-w-6xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>;
  if (overview.error || !overview.data) return <ErrorState title="Your phase guide is not loading yet" detail="Refresh to reconnect with the ideas chosen for your current cycle phase." />;
  const activePhase = overview.data.summary.phase;
  return <div className="mx-auto max-w-6xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9"><header><p className="eyebrow">Cycle phase nutrition ideas</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Eat with your rhythm, not against it.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#806A63]">Find practical food ideas for each menstrual cycle phase, then keep the choices that fit your tastes, culture, budget, hunger, and real life.</p></header><section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#E9D8DD] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className={`phase-pill ${phaseColors[activePhase]}`}>Your current phase: {phaseLabels[activePhase]}</span><h2 className="mt-4 font-display text-3xl">{overview.data.guidance.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#624C53]">{overview.data.guidance.description}</p></div><ShieldCheck className="h-11 w-11 text-[#8B5260]" /></div><div className="mt-5 flex flex-wrap gap-2">{overview.data.guidance.foods.map(food => <span key={food} className="rounded-full bg-white/70 px-3 py-2 text-xs font-bold text-[#754D56]">{food}</span>)}</div></section><section className="mt-8 grid gap-4 md:grid-cols-2">{phaseCards.map(card => <article key={card.phase} className={`rose-card p-5 ${card.phase === activePhase ? "ring-2 ring-[#D48691]" : ""}`}><div className="flex items-center justify-between"><span className={`phase-pill ${phaseColors[card.phase]}`}>{phaseLabels[card.phase]}</span>{card.phase === activePhase && <span className="text-xs font-bold text-[#A74D5C]">Your current chapter</span>}</div><h2 className="mt-4 font-display text-2xl">{card.focus}</h2><p className="mt-3 text-sm leading-6 text-[#785F57]">{card.text}</p><div className="mt-4 flex flex-wrap gap-2">{card.foods.map(food => <span key={food} className="rounded-full bg-[#F8ECE8] px-3 py-1.5 text-xs font-semibold text-[#815E56]">{food}</span>)}</div><p className="mt-5 border-t border-[#EEE0DB] pt-4 text-xs leading-5 text-[#987D75]">{phaseDescriptions[card.phase]}</p></article>)}</section><aside className="mt-7 rounded-2xl bg-[#F6F0EA] p-5 text-sm leading-6 text-[#735D55]"><strong>Let your life lead.</strong> {copy.safety}</aside></div>;
}
