import { trpc } from "@/lib/trpc";
import { copy, displayDate, phaseColors, phaseDescriptions, phaseLabels } from "@/lib/redtent";
import { useLocation } from "wouter";
import { ArrowRight, BookPlus, CalendarPlus, ChevronRight, CirclePlus, Droplets, Loader2, Moon, Sparkles } from "lucide-react";

export default function Home() {
  const { data, isLoading, error } = trpc.dashboard.overview.useQuery();
  const [, setLocation] = useLocation();
  if (isLoading) return <DashboardLoading />;
  if (error || !data) return <ErrorState title="Your daily rhythm is not loading yet" detail="Refresh to reconnect with your Redtent space." />;
  const { summary, guidance, todayWellness, recentJournal, recentFood } = data;
  const daysToPeriod = summary.nextPeriodAt ? Math.max(0, Math.ceil((new Date(summary.nextPeriodAt).getTime() - Date.now()) / 86_400_000)) : null;
  const nextPeriodText = daysToPeriod === null ? "Add your first period" : daysToPeriod === 0 ? "Expected today" : `${daysToPeriod} days away`;

  return (
    <div className="mx-auto max-w-6xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9">
      <header className="flex items-start justify-between gap-4"><div><p className="eyebrow">Your daily cycle check in</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Make today count for tomorrow’s clarity.</h1><p className="mt-2 text-sm text-[#806A63]">A minute of noticing can reveal the patterns your body has been trying to show you.</p></div><button onClick={() => setLocation("/profile")} className="grid h-11 w-11 place-items-center rounded-full bg-[#E9D6D0] text-[#9E4B5A] transition hover:bg-[#DFBDB5]" aria-label="Open your profile">R</button></header>
      <section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#512F37] p-6 text-[#FFF9F7] shadow-[0_18px_50px_rgba(77,36,47,0.22)] sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#EFC9C9]">Cycle day {summary.cycleDay}</p><h2 className="mt-2 font-display text-4xl sm:text-5xl">Your {phaseLabels[summary.phase].toLowerCase()} chapter</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#F0DEDA]">{phaseDescriptions[summary.phase]}</p></div><span className={`phase-pill ${phaseColors[summary.phase]}`}>{summary.confidence === "building" ? "Your pattern is taking shape" : `${summary.confidence} confidence estimate`}</span></div>
        <div className="mt-7 grid grid-cols-2 gap-3 sm:max-w-md"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-[#EFC9C9]">Up next</p><p className="mt-1 font-semibold">{phaseLabels[summary.nextPhase]} phase</p><p className="mt-1 text-xs text-[#EFC9C9]">Starts in {summary.daysUntilNextPhase} {summary.daysUntilNextPhase === 1 ? "day" : "days"}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-[#EFC9C9]">Your next period</p><p className="mt-1 font-semibold">{nextPeriodText}</p><p className="mt-1 text-xs text-[#EFC9C9]">A personal estimate, never a promise</p></div></div>
      </section>
      <section className="mt-7"><div className="flex items-end justify-between"><div><p className="eyebrow">One small check in</p><h2 className="mt-1 font-display text-2xl">What would feel good to notice today?</h2></div><button onClick={() => setLocation("/wellness")} className="text-sm font-semibold text-[#A84D5F]">Complete today’s check in <ChevronRight className="inline h-4 w-4" /></button></div>
        <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><QuickLog icon={CirclePlus} title="Check your mood" subtitle={todayWellness?.mood ? "Today is captured" : "Name how you feel"} onClick={() => setLocation("/wellness")} /><QuickLog icon={CalendarPlus} title="Update your cycle" subtitle="Keep your timing clear" onClick={() => setLocation("/cycle")} /><QuickLog icon={BookPlus} title="Write it down" subtitle="Give the moment a voice" onClick={() => setLocation("/journal")} /><QuickLog icon={Sparkles} title="Explore your meal" subtitle="See food in context" onClick={() => setLocation("/food")} /></div>
      </section>
      <div className="mt-7 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]">
        <section className="rose-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Your phase, your pace</p><h2 className="mt-1 font-display text-2xl">{guidance.title}</h2></div><Droplets className="h-8 w-8 text-[#C86F78]" /></div><p className="mt-4 text-sm leading-6 text-[#755E57]">{guidance.description}</p><div className="mt-5 flex flex-wrap gap-2">{guidance.foods.map(food => <span key={food} className="rounded-full bg-[#F8E9E5] px-3 py-1.5 text-xs font-semibold text-[#835555]">{food}</span>)}</div><button onClick={() => setLocation("/guidance")} className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-[#A84D5F]">Find ideas that fit your phase <ArrowRight className="h-4 w-4" /></button></section>
        <section className="rose-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Your signal for today</p><h2 className="mt-1 font-display text-2xl">Give yourself a real read.</h2></div><Moon className="h-7 w-7 text-[#90708E]" /></div>{todayWellness ? <div className="mt-5 space-y-3 text-sm"><p><span className="text-[#8D756C]">Mood</span><span className="float-right font-semibold capitalize">{todayWellness.mood || "Not set"}</span></p><p><span className="text-[#8D756C]">Energy</span><span className="float-right font-semibold capitalize">{todayWellness.energy || "Not set"}</span></p><p><span className="text-[#8D756C]">Sleep</span><span className="float-right font-semibold capitalize">{todayWellness.sleepQuality || "Not set"}</span></p></div> : <p className="mt-5 text-sm leading-6 text-[#806A63]">Nothing logged yet. Start with what feels true right now.</p>}<button onClick={() => setLocation("/wellness")} className="mt-6 w-full rounded-xl bg-[#F4E5E0] py-2.5 text-sm font-semibold text-[#8E4B57] transition hover:bg-[#EBD2CC]">{todayWellness ? "Refresh today’s check in" : "Start your daily check in"}</button></section>
      </div>
      <section className="mt-7 grid gap-6 lg:grid-cols-2"><RecentList title="Your latest reflections" empty="Your private journal becomes more valuable with every honest sentence." action="Write a reflection" onClick={() => setLocation("/journal")} items={recentJournal.map(entry => ({ title: entry.title, meta: `${phaseLabels[entry.phase]} phase · ${displayDate(entry.entryAt)}` }))} /><RecentList title="Your food insights" empty="Use a food snapshot when you want more context, not more pressure." action="Analyse a meal" onClick={() => setLocation("/food")} items={recentFood.map(entry => ({ title: "Meal snapshot", meta: `${phaseLabels[entry.phase]} phase · ${displayDate(entry.createdAt)}` }))} /></section>
      <p className="mt-8 max-w-3xl text-xs leading-5 text-[#927B74]">{copy.safety}</p>
    </div>
  );
}

function QuickLog({ icon: Icon, title, subtitle, onClick }: { icon: typeof CirclePlus; title: string; subtitle: string; onClick: () => void }) { return <button onClick={onClick} className="rose-card group p-4 text-left transition hover:-translate-y-0.5 hover:shadow-[0_14px_35px_rgba(113,71,61,0.12)]"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#F7E7E3] text-[#B45263]"><Icon className="h-4.5 w-4.5" /></div><p className="mt-4 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-[#8D756C]">{subtitle}</p></button>; }
function RecentList({ title, empty, action, onClick, items }: { title: string; empty: string; action: string; onClick: () => void; items: { title: string; meta: string }[] }) { return <section className="rose-card p-5"><div className="flex items-center justify-between"><h2 className="font-display text-xl">{title}</h2><button onClick={onClick} className="text-xs font-bold text-[#A84D5F]">{action}</button></div>{items.length ? <div className="mt-4 divide-y divide-[#F0E4DF]">{items.map((item, index) => <div key={`${item.title}-${index}`} className="flex items-center justify-between py-3"><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-[#947B73]">{item.meta}</p></div><ChevronRight className="h-4 w-4 text-[#B99D95]" /></div>)}</div> : <p className="mt-4 text-sm leading-6 text-[#806A63]">{empty}</p>}</section>; }
export function DashboardLoading() { return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-7 lg:px-10"><div className="h-10 w-56 animate-pulse rounded-xl bg-[#F1E5E0]" /><div className="mt-7 h-72 animate-pulse rounded-[1.7rem] bg-[#EBD8D3]" /><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-32 animate-pulse rounded-2xl bg-[#F2E8E4]" />)}</div></div>; }
export function ErrorState({ title, detail }: { title: string; detail: string }) { return <div className="mx-auto grid min-h-[60vh] max-w-lg place-items-center px-5 text-center"><div className="rose-card p-8"><p className="font-display text-3xl">{title}</p><p className="mt-3 text-sm leading-6 text-[#806A63]">{detail}</p><button onClick={() => window.location.reload()} className="mt-6 rounded-xl bg-[#A84D5F] px-4 py-2.5 text-sm font-semibold text-white">Reconnect my space</button></div></div>; }
