import { trpc } from "@/lib/trpc";
import { HeartHandshake, Loader2, LockKeyhole, Sparkles } from "lucide-react";
import { useMemo } from "react";

export default function PartnerCompanionPage() {
  const token = useMemo(() => new URLSearchParams(window.location.search).get("token") || "", []);
  const companion = trpc.partner.companion.useQuery({ token }, { enabled: token.length >= 20 });
  if (!token) return <Unavailable title="This companion link is incomplete." detail="Ask the person who shared it with you to create a new private link from Redtent." />;
  if (companion.isLoading) return <div className="grid min-h-screen place-items-center bg-[#241C22] text-white"><Loader2 className="h-7 w-7 animate-spin text-[#F3B5B6]" /></div>;
  if (companion.error || !companion.data) return <Unavailable title="This companion link is no longer available." detail="It may have been revoked or replaced. Redtent keeps access under the account owner’s control." />;
  const { ownerName, partnerName, support, browserAlertsEnabled, emailAlertsEnabled } = companion.data;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,_rgba(177,90,110,0.38),_transparent_34%),linear-gradient(160deg,#241C22_0%,#432B38_46%,#6D3D4A_100%)] px-4 py-8 text-[#FFF9F7] sm:px-7"><div className="mx-auto max-w-xl"><header className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#D57A88] font-display text-xl text-white">R</div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#EABCC2]">Redtent companion</p><h1 className="font-display text-2xl">{ownerName}&rsquo;s shared support cue</h1></div></header><section className="mt-7 rounded-[1.8rem] border border-white/15 bg-[#281F27]/80 p-6 shadow-[0_18px_60px_rgba(0,0,0,0.26)] backdrop-blur"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#DDB0D2]">A private check-in</p><h2 className="mt-2 font-display text-3xl text-[#F5D5DF]">{support.title}</h2><p className="mt-4 text-base leading-7 text-[#F7E7EA]">{support.detail}</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/5 rounded-full bg-gradient-to-r from-[#D97188] via-[#F2B55B] to-[#D9A8CB]" /></div><p className="mt-3 text-sm text-[#EECED3]">This is an estimated cycle moment, not a medical statement or a reason to assume how {ownerName} feels.</p></section><section className="mt-5 grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-white/15 bg-white/8 p-5"><HeartHandshake className="h-5 w-5 text-[#F0B6C5]" /><h2 className="mt-3 font-display text-2xl">Be there gently.</h2><p className="mt-2 text-sm leading-6 text-[#F0DDE1]">Ask what would help. Offer a small practical kindness. Listen without trying to solve everything.</p></article><article className="rounded-2xl border border-white/15 bg-white/8 p-5"><Sparkles className="h-5 w-5 text-[#F0B6C5]" /><h2 className="mt-3 font-display text-2xl">Keep it personal.</h2><p className="mt-2 text-sm leading-6 text-[#F0DDE1]">{partnerName ? `${partnerName}, ` : ""}let their answer lead. The best support is the support they actually want today.</p></article></section><section className="mt-5 rounded-2xl border border-white/15 bg-[#342430]/80 p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#EABCC2]">Optional reminders</p><p className="mt-2 text-sm leading-6 text-[#F0DDE1]">{browserAlertsEnabled || emailAlertsEnabled ? "This companion invitation can include owner-approved reminders when delivery is available. You can always choose not to receive them." : "The account owner has not turned on companion reminders for this link."}</p><p className="mt-4 inline-flex gap-2 text-xs leading-5 text-[#E7C9D0]"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />{support.privacy}</p></section><p className="mt-6 text-center text-xs leading-5 text-[#D9BCC5]">Redtent shares general wellness information, not medical advice.</p></div></main>;
}

function Unavailable({ title, detail }: { title: string; detail: string }) { return <main className="grid min-h-screen place-items-center bg-[#241C22] px-5 text-center text-[#FFF9F7]"><section className="max-w-md rounded-[1.8rem] border border-white/15 bg-white/8 p-7"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#D57A88] font-display text-xl">R</div><h1 className="mt-5 font-display text-3xl">{title}</h1><p className="mt-3 text-sm leading-6 text-[#EECED3]">{detail}</p></section></main>; }
