import { phaseLabels } from "@/lib/redtent";
import { trpc } from "@/lib/trpc";
import { ChartNoAxesCombined, ChevronRight, Loader2, Sparkles } from "lucide-react";
import { useLocation } from "wouter";
import { ErrorState } from "./Home";

export default function PatternsPage() {
  const overview = trpc.dashboard.overview.useQuery();
  const [, setLocation] = useLocation();
  if (overview.isLoading) return <Loading />;
  if (overview.error || !overview.data) return <ErrorState title="Your patterns are taking a moment" detail="Refresh to reconnect with the entries in your Redtent space." />;
  const { patterns, summary, challenge } = overview.data;
  return <div className="mx-auto max-w-5xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9">
    <header className="max-w-3xl"><p className="eyebrow">Your Patterns</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">The patterns you choose to make visible.</h1><p className="mt-3 text-sm leading-6 text-[#806A63]">Redtent only reflects connections in your own entries. These are observations, not diagnoses, proof, or a substitute for professional care.</p></header>
    <section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#512F37] p-6 text-[#FFF9F7] shadow-[0_18px_50px_rgba(77,36,47,0.22)] sm:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10"><ChartNoAxesCombined className="h-6 w-6 text-[#F5C8C9]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#EFC9C9]">Your current context</p><h2 className="mt-2 font-display text-3xl">Cycle day {summary.cycleDay}, estimated {phaseLabels[summary.phase].toLowerCase()} phase</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#F0DEDA]">The more cycle, Food Lens, daily check-in, and Your Space entries you choose to add, the more personal these reflections can become.</p></div></div></section>
    <section className="mt-7"><div><p className="eyebrow">We have noticed</p><h2 className="mt-1 font-display text-2xl">Your personal observations</h2></div>{patterns.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{patterns.map(pattern => <article key={pattern.id} className="rose-card p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#F8E8E5] text-[#B45263]"><Sparkles className="h-4 w-4" /></div><span className="rounded-full bg-[#F4E5E0] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#8E4B57]">{pattern.confidence} signal</span></div><h3 className="mt-4 text-base font-bold text-[#5E3E38]">{pattern.title}</h3><p className="mt-2 text-sm leading-6 text-[#806A63]">{pattern.detail}</p></article>)}</div> : <div className="rose-card mt-4 p-6"><h3 className="font-display text-2xl">Your first pattern starts with a few moments.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#806A63]">Try a quick check-in, add a cycle date, snap a meal, or write in Your Space. Redtent will not invent a pattern before your entries have something real to show.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => setLocation("/wellness")} className="rounded-xl bg-[#A84D5F] px-4 py-2.5 text-sm font-semibold text-white">Start a daily check-in</button><button onClick={() => setLocation("/food")} className="rounded-xl bg-[#F4E5E0] px-4 py-2.5 text-sm font-semibold text-[#8E4B57]">Open Food Lens</button></div></div>}</section>
    <section className="mt-7 rounded-[1.7rem] border border-[#E7D8D3] bg-[#FFFDFB] p-5 sm:p-7"><p className="eyebrow">Your 30-Day Know Your Body Challenge</p><h2 className="mt-1 font-display text-2xl">Build your report, gently and at your own pace.</h2><p className="mt-2 text-sm leading-6 text-[#806A63]">You have {challenge.progress} of 30 moments across your cycle, wellness, Food Lens, and Your Space.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#F4E7E3]"><div className="h-full rounded-full bg-[#C86F78]" style={{ width: `${Math.max(4, (challenge.progress / 30) * 100)}%` }} /></div><button onClick={() => setLocation("/")} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-[#A84D5F]">Continue today <ChevronRight className="h-4 w-4" /></button></section>
  </div>;
}

function Loading() { return <div className="mx-auto max-w-5xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>; }
