import { MomentReflectionCard } from "@/components/MomentReflectionCard";
import { PreparationChecklistCard } from "@/components/PreparationChecklistCard";
import { phaseLabels } from "@/lib/redtent";
import { trpc } from "@/lib/trpc";
import { ChartNoAxesCombined, ChevronRight, HeartHandshake, Loader2, Sparkles } from "lucide-react";
import { useLocation } from "wouter";
import { ErrorState } from "./Home";

export default function PatternsPage() {
  const overview = trpc.dashboard.overview.useQuery();
  const trends = trpc.trends.dashboard.useQuery();
  const [, setLocation] = useLocation();
  if (overview.isLoading || trends.isLoading) return <Loading />;
  if (overview.error || !overview.data || trends.error || !trends.data) return <ErrorState title="Your patterns are taking a moment" detail="Refresh to reconnect with the entries in your Redtent space." />;
  const { patterns, summary, challenge } = overview.data;
  const { sample, moodCounts, energyCounts, topSignals, recentCycles, recentReflections, note } = trends.data;
  return <div className="mx-auto max-w-5xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9">
    <header className="max-w-3xl"><p className="eyebrow">Your Patterns</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Your data, reflected with care.</h1><p className="mt-3 text-sm leading-6 text-[#806A63]">This private dashboard only organizes the cycle dates, check-ins, routines, and reflections you chose to log. It does not diagnose, predict, or decide what your body should feel.</p></header>
    <section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#512F37] p-6 text-[#FFF9F7] shadow-[0_18px_50px_rgba(77,36,47,0.22)] sm:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10"><ChartNoAxesCombined className="h-6 w-6 text-[#F5C8C9]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#EFC9C9]">Your current context</p><h2 className="mt-2 font-display text-3xl">Cycle day {summary.cycleDay}, estimated {phaseLabels[summary.phase].toLowerCase()} phase</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#F0DEDA]">You have logged {sample.cyclesTracked} cycle {sample.cyclesTracked === 1 ? "start" : "starts"}, {sample.checkIns} check-ins, and {sample.reflections} what-helped reflection{sample.reflections === 1 ? "" : "s"}.</p></div></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Metric label="Cycle starts" value={sample.cyclesTracked} detail="Timing you logged" /><Metric label="Wellness check-ins" value={sample.checkIns} detail="Mood, energy, sleep, and signals" /><Metric label="What helped notes" value={sample.reflections} detail="Private reflections" /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><DistributionCard title="Mood check-ins" detail="A count of your recorded mood words" values={moodCounts} /><DistributionCard title="Energy check-ins" detail="A count of your recorded energy levels" values={energyCounts} /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><article className="rose-card p-5"><p className="eyebrow">Recent cycles</p><h2 className="mt-1 font-display text-2xl">Timing, not a promise.</h2>{recentCycles.length ? <div className="mt-5 space-y-3">{recentCycles.map((cycle, index) => <div key={cycle.startAt.toISOString()} className="flex items-center justify-between rounded-xl bg-[#F8EAE6] px-4 py-3"><span className="text-sm font-semibold text-[#65453F]">Cycle {recentCycles.length - index}</span><span className="text-sm text-[#806A63]">{cycle.length ? `${cycle.length} days to the next logged start` : "Add another start to compare timing"}</span></div>)}</div> : <EmptyTrend text="Add a period start to begin your personal cycle record." />}</article><article className="rose-card p-5"><p className="eyebrow">Signals you logged</p><h2 className="mt-1 font-display text-2xl">What has appeared in check-ins.</h2>{topSignals.length ? <div className="mt-5 flex flex-wrap gap-2">{topSignals.map(signal => <span key={signal.label} className="rounded-full bg-[#F8EAE6] px-3 py-2 text-sm font-semibold text-[#765A52]">{signal.label} <span className="text-[#A84D5F]">{signal.count}</span></span>)}</div> : <EmptyTrend text="When you choose body signals in Wellness, they can be summarized here." />}</article></section>
    <section className="mt-7"><div><p className="eyebrow">We have noticed</p><h2 className="mt-1 font-display text-2xl">Your personal observations</h2></div>{patterns.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{patterns.map(pattern => <article key={pattern.id} className="rose-card p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#F8E8E5] text-[#B45263]"><Sparkles className="h-4 w-4" /></div><span className="rounded-full bg-[#F4E5E0] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#8E4B57]">{pattern.confidence} signal</span></div><h3 className="mt-4 text-base font-bold text-[#5E3E38]">{pattern.title}</h3><p className="mt-2 text-sm leading-6 text-[#806A63]">{pattern.detail}</p></article>)}</div> : <div className="rose-card mt-4 p-6"><h3 className="font-display text-2xl">Your first pattern starts with a few moments.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#806A63]">Try a quick check-in, add a cycle date, or leave a note about what helped. Redtent will not invent a pattern before your entries have something real to show.</p><button onClick={() => setLocation("/wellness")} className="mt-5 rounded-xl bg-[#A84D5F] px-4 py-2.5 text-sm font-semibold text-white">Start a daily check-in</button></div>}</section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><PreparationChecklistCard /><MomentReflectionCard /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><article className="rose-card p-5"><div className="flex items-start gap-3"><HeartHandshake className="mt-1 h-5 w-5 shrink-0 text-[#A84D5F]" /><div><p className="eyebrow">What helped before</p><h2 className="mt-1 font-display text-2xl">Your own words, ready to revisit.</h2></div></div>{recentReflections.length ? <div className="mt-4 space-y-3">{recentReflections.map(reflection => <div key={`${reflection.moment}-${reflection.entryAt.toISOString()}`} className="rounded-xl bg-[#F8EAE6] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#A84D5F]">{reflection.moment.replace("-", " ")}</p><p className="mt-1 text-sm leading-6 text-[#765B54]">{reflection.whatHelped}</p></div>)}</div> : <EmptyTrend text="Your saved what-helped reflections will stay here for future you." />}</article><article className="rounded-[1.7rem] border border-[#E7D8D3] bg-[#FFFDFB] p-5"><p className="eyebrow">Your 30-Day Know Your Body Challenge</p><h2 className="mt-1 font-display text-2xl">Build your report, gently and at your own pace.</h2><p className="mt-2 text-sm leading-6 text-[#806A63]">You have {challenge.progress} of 30 moments across your cycle, wellness, Food Lens, and Your Space.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#F4E7E3]"><div className="h-full rounded-full bg-[#C86F78]" style={{ width: `${Math.max(4, (challenge.progress / 30) * 100)}%` }} /></div><button onClick={() => setLocation("/")} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-[#A84D5F]">Continue today <ChevronRight className="h-4 w-4" /></button></article></section>
    <aside className="mt-7 rounded-2xl bg-[#F3ECEE] p-5 text-sm leading-6 text-[#725E68]">{note}</aside>
  </div>;
}

function Metric({ label, value, detail }: { label: string; value: number; detail: string }) { return <article className="rose-card p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9A7370]">{label}</p><p className="mt-2 font-display text-4xl text-[#5E3E38]">{value}</p><p className="mt-1 text-xs leading-5 text-[#806A63]">{detail}</p></article>; }
function DistributionCard({ title, detail, values }: { title: string; detail: string; values: Array<{ label: string; count: number }> }) { const max = Math.max(1, ...values.map(value => value.count)); return <article className="rose-card p-5"><p className="eyebrow">Personal trends</p><h2 className="mt-1 font-display text-2xl">{title}</h2><p className="mt-2 text-sm text-[#806A63]">{detail}</p><div className="mt-5 space-y-3">{values.map(value => <div key={value.label}><div className="mb-1 flex justify-between text-xs font-semibold capitalize text-[#725752]"><span>{value.label}</span><span>{value.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#F3E3DE]"><div className="h-full rounded-full bg-[#C86F78]" style={{ width: `${(value.count / max) * 100}%` }} /></div></div>)}</div></article>; }
function EmptyTrend({ text }: { text: string }) { return <p className="mt-4 rounded-xl bg-[#F8EAE6] px-4 py-3 text-sm leading-6 text-[#806A63]">{text}</p>; }
function Loading() { return <div className="mx-auto max-w-5xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>; }
