import { MomentReflectionCard } from "@/components/MomentReflectionCard";
import { PreparationChecklistCard } from "@/components/PreparationChecklistCard";
import { phaseLabels } from "@/lib/redtent";
import { trpc } from "@/lib/trpc";
import { CalendarRange, ChartNoAxesCombined, ChevronRight, Download, HeartHandshake, Loader2, Sparkles } from "lucide-react";
import { useLocation } from "wouter";
import { ErrorState } from "./Home";
import { downloadTrendExport } from "@/lib/trendExport";

export default function PatternsPage() {
  const overview = trpc.dashboard.overview.useQuery();
  const trends = trpc.trends.dashboard.useQuery();
  const [, setLocation] = useLocation();
  if (overview.isLoading || trends.isLoading) return <Loading />;
  if (overview.error || !overview.data || trends.error || !trends.data) return <ErrorState title="Your patterns are taking a moment" detail="Refresh to reconnect with the entries in your Redtent space." />;
  const { patterns, summary, challenge } = overview.data;
  const { sample, timing, coverage, moodCounts, energyCounts, topSignals, recentCycles, recentReflections, note } = trends.data;
  return <div className="mx-auto max-w-5xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9">
    <header className="flex flex-wrap items-end justify-between gap-4"><div className="max-w-3xl"><p className="eyebrow">Your Patterns</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Your cycles, made easier to compare.</h1><p className="mt-3 text-sm leading-6 text-[#806A63]">This private dashboard organizes the cycle dates, check-ins, routines, and reflections you chose to log. It helps you see your own record across cycles without diagnosing, predicting, or deciding what your body should feel.</p></div><button type="button" onClick={() => downloadTrendExport(trends.data)} className="inline-flex items-center gap-2 rounded-xl border border-[#D6B6B3] bg-[#FFFDFB] px-4 py-2.5 text-sm font-bold text-[#8E4352] shadow-sm hover:bg-[#FCECEE]"><Download className="h-4 w-4" /> Export my trends</button></header>
    <section className="mt-7 overflow-hidden rounded-[1.7rem] bg-[#512F37] p-6 text-[#FFF9F7] shadow-[0_18px_50px_rgba(77,36,47,0.22)] sm:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10"><ChartNoAxesCombined className="h-6 w-6 text-[#F5C8C9]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#EFC9C9]">Your current context</p><h2 className="mt-2 font-display text-3xl">Cycle day {summary.cycleDay}, estimated {phaseLabels[summary.phase].toLowerCase()} phase</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#F0DEDA]">You have logged {sample.cyclesTracked} cycle {sample.cyclesTracked === 1 ? "start" : "starts"}, {sample.checkIns} check-ins, and {sample.reflections} what-helped reflection{sample.reflections === 1 ? "" : "s"}.</p></div></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Cycle starts" value={sample.cyclesTracked} detail="Starts you logged" /><Metric label="Average timing" value={timing.averageLength ? `${timing.averageLength}d` : "—"} detail={timing.intervalsTracked ? `From ${timing.intervalsTracked} completed interval${timing.intervalsTracked === 1 ? "" : "s"}` : "Add two starts to compare"} /><Metric label="Timing range" value={timing.variation !== null ? `${timing.variation}d` : "—"} detail={timing.shortestLength !== null && timing.longestLength !== null ? `${timing.shortestLength}–${timing.longestLength} days logged` : "No range yet"} /><Metric label="Check-in coverage" value={`${coverage.cyclesWithCheckIns}/${sample.cyclesTracked || 0}`} detail="Cycles with a check-in" /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-[1.45fr_0.85fr]"><article className="rose-card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Cycle rhythm</p><h2 className="mt-1 font-display text-2xl">Your recent logged timing</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#806A63]">Each bar is one cycle start you logged. Completed bars show days to your next logged start, not a promise about a future period.</p></div><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#F8E8E5] text-[#A84D5F]"><CalendarRange className="h-5 w-5" /></div></div><CycleRhythmChart cycles={recentCycles} /></article><article className="rounded-[1.7rem] bg-[#F2E6E3] p-5 sm:p-6"><p className="eyebrow">Your logging picture</p><h2 className="mt-1 font-display text-2xl text-[#51343A]">A fuller record, one moment at a time.</h2><div className="mt-5 space-y-4"><Coverage label="Cycles with check-ins" value={coverage.cyclesWithCheckIns} total={sample.cyclesTracked} /><Coverage label="Cycles with what-helped notes" value={coverage.cyclesWithReflections} total={sample.cyclesTracked} /><Coverage label="Total wellness check-ins" value={sample.checkIns} total={Math.max(7, sample.checkIns)} /></div><p className="mt-5 text-xs leading-5 text-[#806A63]">There is no target to reach. More notes simply give future you more of your own context to revisit.</p></article></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><DistributionCard title="Mood check-ins" detail="A count of your recorded mood words" values={moodCounts} /><DistributionCard title="Energy check-ins" detail="A count of your recorded energy levels" values={energyCounts} /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><article className="rose-card p-5"><p className="eyebrow">Recent cycles</p><h2 className="mt-1 font-display text-2xl">Timing, check-ins, and reflections.</h2>{recentCycles.length ? <div className="mt-5 space-y-3">{recentCycles.map((cycle, index) => <div key={cycle.startAt.toISOString()} className="rounded-xl bg-[#F8EAE6] px-4 py-3"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-[#65453F]">Cycle {recentCycles.length - index}</span><span className="text-xs font-semibold text-[#8A625B]">{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(cycle.startAt)}</span></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-[#806A63]"><span>{cycle.length ? `${cycle.length} days to next logged start` : "Current or latest logged cycle"}</span><span>{cycle.checkIns} check-in{cycle.checkIns === 1 ? "" : "s"}</span><span>{cycle.reflectionCount} reflection{cycle.reflectionCount === 1 ? "" : "s"}</span></div></div>)}</div> : <EmptyTrend text="Add a period start to begin your personal cycle record." />}</article><article className="rose-card p-5"><p className="eyebrow">Signals you logged</p><h2 className="mt-1 font-display text-2xl">What has appeared in check-ins.</h2>{topSignals.length ? <div className="mt-5 flex flex-wrap gap-2">{topSignals.map(signal => <span key={signal.label} className="trend-badge rounded-full bg-[#F8EAE6] px-3 py-2 text-sm font-semibold text-[#765A52]">{signal.label} <span>{signal.count}</span></span>)}</div> : <EmptyTrend text="When you choose body signals in Wellness, they can be summarized here." />}</article></section>
    <section className="mt-7"><div><p className="eyebrow">We have noticed</p><h2 className="mt-1 font-display text-2xl">Your personal observations</h2></div>{patterns.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{patterns.map(pattern => <article key={pattern.id} className="rose-card p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#F8E8E5] text-[#B45263]"><Sparkles className="h-4 w-4" /></div><span className="confidence-badge rounded-full bg-[#F4E5E0] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#8E4B57]">{pattern.confidence} signal</span></div><h3 className="mt-4 text-base font-bold text-[#5E3E38]">{pattern.title}</h3><p className="mt-2 text-sm leading-6 text-[#806A63]">{pattern.detail}</p></article>)}</div> : <div className="rose-card mt-4 p-6"><h3 className="font-display text-2xl">Your first pattern starts with a few moments.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#806A63]">Try a quick check-in, add a cycle date, or leave a note about what helped. Redtent will not invent a pattern before your entries have something real to show.</p><button onClick={() => setLocation("/wellness")} className="mt-5 rounded-xl bg-[#A84D5F] px-4 py-2.5 text-sm font-semibold text-white">Start a daily check-in</button></div>}</section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><PreparationChecklistCard /><MomentReflectionCard /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2"><article className="rose-card p-5"><div className="flex items-start gap-3"><HeartHandshake className="mt-1 h-5 w-5 shrink-0 text-[#A84D5F]" /><div><p className="eyebrow">What helped before</p><h2 className="mt-1 font-display text-2xl">Your own words, ready to revisit.</h2></div></div>{recentReflections.length ? <div className="mt-4 space-y-3">{recentReflections.map(reflection => <div key={`${reflection.moment}-${reflection.entryAt.toISOString()}`} className="rounded-xl bg-[#F8EAE6] p-3"><p className="text-xs font-bold uppercase tracking-wide text-[#A84D5F]">{reflection.moment.replace("-", " ")}</p><p className="mt-1 text-sm leading-6 text-[#765B54]">{reflection.whatHelped}</p></div>)}</div> : <EmptyTrend text="Your saved what-helped reflections will stay here for future you." />}</article><article className="rounded-[1.7rem] border border-[#E7D8D3] bg-[#FFFDFB] p-5"><p className="eyebrow">Your 30-Day Know Your Body Challenge</p><h2 className="mt-1 font-display text-2xl">Build your report, gently and at your own pace.</h2><p className="mt-2 text-sm leading-6 text-[#806A63]">You have {challenge.progress} of 30 moments across your cycle, wellness, Food Lens, and Your Space.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#F4E7E3]"><div className="h-full rounded-full bg-[#C86F78]" style={{ width: `${Math.max(4, (challenge.progress / 30) * 100)}%` }} /></div><button onClick={() => setLocation("/")} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-[#A84D5F]">Continue today <ChevronRight className="h-4 w-4" /></button></article></section>
    <aside className="mt-7 rounded-2xl bg-[#F3ECEE] p-5 text-sm leading-6 text-[#725E68]">{note}</aside>
  </div>;
}

type TrendCycle = { startAt: Date; length: number | null; checkIns: number; reflectionCount: number };
function Metric({ label, value, detail }: { label: string; value: number | string; detail: string }) { return <article className="rose-card p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#9A7370]">{label}</p><p className="mt-2 font-display text-4xl text-[#5E3E38]">{value}</p><p className="mt-1 text-xs leading-5 text-[#806A63]">{detail}</p></article>; }
function Coverage({ label, value, total }: { label: string; value: number; total: number }) { const ratio = total ? Math.min(100, Math.round((value / total) * 100)) : 0; return <div><div className="mb-1.5 flex items-baseline justify-between gap-3 text-xs font-semibold text-[#6F4C49]"><span>{label}</span><span>{value}/{total || 0}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/80"><div className="h-full rounded-full bg-[#B85C6A] transition-[width] duration-300" style={{ width: `${ratio}%` }} /></div></div>; }
function CycleRhythmChart({ cycles }: { cycles: TrendCycle[] }) { const completed = cycles.filter(cycle => cycle.length !== null).map(cycle => cycle.length || 0); const max = Math.max(1, ...completed); if (!cycles.length) return <EmptyTrend text="Add two period starts to compare timing across your own logged cycles." />; return <div className="mt-6 grid min-h-44 grid-cols-4 items-end gap-3 border-b border-[#EADBD6] pb-3">{cycles.map((cycle, index) => { const height = cycle.length ? Math.max(22, Math.round((cycle.length / max) * 116)) : 20; return <div key={cycle.startAt.toISOString()} className="flex min-w-0 flex-col items-center gap-2"><span className="text-xs font-bold text-[#76514D]">{cycle.length ? `${cycle.length}d` : "latest"}</span><div className={`w-full max-w-16 rounded-t-2xl ${cycle.length ? "bg-[#C66E78]" : "bg-[#E8D8D3]"}`} style={{ height }} /><span className="text-[10px] font-semibold uppercase tracking-wide text-[#977B72]">C{cycles.length - index}</span></div>; })}</div>; }
function DistributionCard({ title, detail, values }: { title: string; detail: string; values: Array<{ label: string; count: number }> }) { const max = Math.max(1, ...values.map(value => value.count)); return <article className="rose-card p-5"><p className="eyebrow">Personal trends</p><h2 className="mt-1 font-display text-2xl">{title}</h2><p className="mt-2 text-sm text-[#806A63]">{detail}</p><div className="mt-5 space-y-3">{values.map(value => <div key={value.label}><div className="mb-1 flex justify-between text-xs font-semibold capitalize text-[#725752]"><span>{value.label}</span><span>{value.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#F3E3DE]"><div className="h-full rounded-full bg-[#C86F78]" style={{ width: `${(value.count / max) * 100}%` }} /></div></div>)}</div></article>; }
function EmptyTrend({ text }: { text: string }) { return <p className="mt-4 rounded-xl bg-[#F8EAE6] px-4 py-3 text-sm leading-6 text-[#806A63]">{text}</p>; }
function Loading() { return <div className="mx-auto max-w-5xl px-4 py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B45263]" /></div>; }
