import { useAuth } from "@/_core/hooks/useAuth";
import { copy } from "@/lib/redtent";
import { LockKeyhole, LogOut, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function ProfilePage() {
  const { user, logout } = useAuth();
  return <div className="mx-auto max-w-3xl px-4 pb-8 pt-5 sm:px-7 lg:px-10 lg:pt-9"><header><p className="eyebrow">Your Redtent account</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">Your story stays yours.</h1><p className="mt-2 text-sm text-[#806A63]">See how Redtent protects your personal cycle, wellness, journal, and food insight records.</p></header><section className="rose-card mt-7 p-6"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#C76E79] text-xl font-bold text-white">{user?.name?.slice(0, 1).toUpperCase() || "R"}</div><div><h2 className="font-display text-2xl">{user?.name || "Redtent member"}</h2><p className="mt-1 text-sm text-[#806A63]">{user?.email || "Your secure Redtent account"}</p></div></div></section><section className="mt-6 grid gap-4 sm:grid-cols-2"><article className="rose-card p-5"><LockKeyhole className="h-6 w-6 text-[#A94F60]" /><h2 className="mt-4 font-display text-xl">Private by design</h2><p className="mt-2 text-sm leading-6 text-[#806A63]">{copy.privateSpace}</p></article><article className="rose-card p-5"><ShieldCheck className="h-6 w-6 text-[#7A9677]" /><h2 className="mt-4 font-display text-xl">Clear, careful insights</h2><p className="mt-2 text-sm leading-6 text-[#806A63]">We make uncertainty visible. Cycle timing and food observations are helpful estimates, not diagnoses or medical advice.</p></article></section><section className="mt-6 rounded-2xl bg-[#F3ECEE] p-5"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-[#9A5A68]" /><div><h2 className="font-semibold">How food insights work</h2><p className="mt-1 text-sm leading-6 text-[#725E68]">When you choose a meal photo, an AI vision model offers a structured observation. It cannot see every ingredient, portion, preparation method, or personal need with certainty.</p></div></div></section><Button onClick={logout} variant="outline" className="mt-7 border-[#DDBFC0] text-[#994755] hover:bg-[#FCECEE]"><LogOut className="mr-2 h-4 w-4" /> Sign out securely</Button></div>;
}
